default_password: admin
default_cluster: cluster01
os_password: 123456
docker_version: docker-ce-17.03.2.ce-1.el7.centos.x86_64
rancher_version: v2.1.7
kubernetes_version: v1.11.9-rancher1-1

server:
  start: true
  cpus: 4
  memory: 16666
master:
  start: true
  count: 3
  cpus: 4
  memory: 16666
  worker: false
  disksize: 2055GB
node:
  start: true
  count: 6
  cpus: 8
  memory: 16666
  disksize: 1055GB
ip:
  server: 192.168.1.30
  master: 192.168.1.31
  node:   192.168.1.51
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
