default_password: admin
default_cluster: cluster01
version: latest
kubernetes_version: v1.13.5-rancher1-2
synced_folder: synced_folder

server:
  start: true
  cpus: 2
  memory: 1500
master:
  start: true
  count: 1
  cpus: 2
  memory: 1500
node:
  start: true
  count: 1
  cpus: 4
  memory: 1500
ip:
  server: 192.168.1.30
  master: 192.168.1.31
  node:   192.168.1.51
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
