default_password: admin
default_cluster: cluster01
version: v2.1.x
kubernetes_version: v1.13.5-rancher1-2

server:
  start: true
  cpus: 4
  memory: 3750
master:
  start: true
  count: 3
  cpus: 4
  memory: 3750
  worker: false
  disksize: 1055GB
node:
  start: true
  count: 9
  cpus: 8
  memory: 10720
  disksize: 1055GB
ip:
  server: 192.168.1.30
  master: 192.168.1.31
  node:   192.168.1.51
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
