default_password: admin
default_cluster: cluster01
os_password: 123456
docker_version: docker-ce
rancher_version: v2.2.2-rc11
kubernetes_version: v1.11.9-rancher1-1

server:
  start: true
  cpus: 4
  memory: 16666
master:
  start: true
  count: 6
  cpus: 8
  memory: 33333
  worker: true
  disksize: 2055GB
node:
  start: false
  count: 9
  cpus: 8
  memory: 10720
  disksize: 1055GB
ip:
  server: 192.168.1.30
  master: 192.168.1.31
  node:   192.168.1.51
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
