default_name: btadmin
default_password: btadmin
default_auth_path: btlogin
bt:
  start: true
  cpus: 1
  memory: 1500
  disksize: 1055GB
ip:
  bt: 192.168.1.127
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
