default_name: btadmin
default_password: btadmin
default_auth_path: btlogin
bt:
  start: true
  cpus: 4
  memory: 4096
ip:
  bt: 192.168.1.10
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: public_network
  # network_type: private_network
