# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

x = YAML.load_file('config.yaml')
puts "Config: #{x.inspect}\n\n"

$private_nic_type = x.fetch('net').fetch('private_nic_type')

Vagrant.configure("2") do |config|
  if x.fetch('bt').fetch('start')
    config.vm.define "bt" do |server|
        c = x.fetch('bt')
        server.vm.box= "centos/7"
        server.disksize.size = c.fetch('disksize')
        server.vm.provider :virtualbox do |v|
          v.cpus = c.fetch('cpus')
          v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0') and x.fetch('linked_clones')
          v.memory = c.fetch('memory')
          v.name = "bt"
        end
        server.vm.network x.fetch('net').fetch('network_type'), ip: x.fetch('ip').fetch('bt') , nic_type: $private_nic_type
        server.vm.hostname = "bt"
        server.vm.provision "shell", path: "scripts/disksize.sh"
        server.vm.provision "shell", path: "scripts/bt_install.sh", args: [x.fetch('ip').fetch('bt'),x.fetch('default_auth_path'), x.fetch('default_name'), x.fetch('default_password')]
    end   
  end 
end